### ISSUE TITLE
No BeautifulSoup parser was explicitly specified

### ISSUE THREAD

**Issue by Genda1ph** [classner/better_code_samples#1]
Hello.
With recent BeautifulSoup (on Python 3.5) I'm getting this warning:

/home/gendalph-manjaro/Blog/env/lib/python3.5/site-packages/bs4/**init**.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html5lib")

  markup_type=markup_type))

This could be fixed by specifying parser in dependencies and setting it in BS call, like so:
soup = BeautifulSoup(content, "html5lib")

**Comment by Genda1ph** [comment]
And here's the patch:
[fix.txt](https://github.com/classner/better_code_samples/files/67672/fix.txt)

**Comment by classner** [comment]
Thanks pointing it out and, even more, for providing the fix right away! :) Has been applied!

**Comment by kevinmaresca** [comment]
how do you use that patch?

**Comment by Genda1ph** [comment]
@kevinmaresca this is an old issue, you might want to use a version where this has been fixed, or just download and apply patch manually.

**Comment by kevinmaresca** [comment]
@Genda1ph I'm using BeautifulSoup4, but I'm still struggling quite a bit. I am very new to all this. What I've done so far is this: 

from bs4 import BeautifulSoup
import requests
url = 'https://www.ncdc.noaa.gov/cag/national/time-series'
r = requests.get(url)
soup = BeautifulSoup(url, "html5lib")

However, I get an error ('You should probably use and HTTP client...'). Do you see anything wrong with it? Again, this might be totally wrong; I started looking at this stuff yesterday. Thanks

**Comment by Genda1ph** [comment]
I'm not a Python dev and this is completely unrelated issue.
Please, search for help elsewhere and don't necropost, especially not in GitHub issues.
